package objects;

public enum Livro {
	AS_CRONICAS_DO_GELO_E_FOGO,
	HARRY_POTTER,
    O_SENHOR_DOS_ANEIS,
    O_CASO_DE_CHARLES_DEXTERWARD,
    UMA_BREVE_HISTORIA_DO_TEMPO,
    ASSIM_FALOU_ZARATUSTRA,
    APOLOGIA_DE_SOCRATES
}
